### ISSUE TITLE
Appium-sdb v1.0.0-beta source-map-support issue

### ISSUE THREAD

**Issue by Sajoha** [Samsung/appium-sdb#7]
The published version of this package still uses an older version of source-map-support which doesn't have the buffer deprecation fix in place [here](https://github.com/evanw/node-source-map-support/commit/f520e54b0bdcf1cc61e87031fb16323638efe5d9#diff-f332e9a051ea7f7b602a3d633c506d30R165). Currently installs `0.4.8` where the issue was patched in `0.5.5`. I see you've bumped to `0.5.9` in the package.json, would it be possible to publish this change please?

**Comment by flyofsky** [comment]
published 1.0.1-beta
